### PR TITLE
fix: typo for module util-promisifyall

### PR DESCRIPTION
**Pull request by dunse**

### CODE REVIEW

**Comment by dunse** [comment]
Yes, it doesn't work as the package name is all lower-case:
`    "util-promisifyall": "^1.0.4"`

**Comment by Snirpo** [comment]
I've tested it on Linux, and it indeed breaks. On Windows it does work with camelcase. I will accept your merge request. Thank you!

**Comment by Snirpo** [comment]
Fixed in 1.0.2

**Comment by dunse** [comment]
It is working correctly now, cheers!

**Pull request merged**
